---
model_list:
  - model_name: Mistral-Large
    litellm_params:
      model: azure_ai/Mistral-Large-2411
      api_base: https://xxxx.models.ai.azure.com/
      api_key: ""
  - model_name: gpt-4o
    litellm_params:
      model: azure_ai/gpt-4o
      api_base: https://x.services.ai.azure.com/
      api_key: ""
      api_version: "2024-10-21"
  - model_name: Mistral-7b
    litellm_params:
      model: openai/mistralai/Mistral-7B-Instruct-v0.3
      api_key: ""
      api_base: https://vllm.srvitkcaiaavllm01.itkdev.dk/v1
