---
model_list:
  - model_name: Mistral-Large
    litellm_params:
      model: azure_ai/Mistral-Large-2411
      api_base: https://xxxx.models.ai.azure.com/
      api_key: ""
  - model_name: gpt-4o
    litellm_params:
      model: azure_ai/gpt-4o
      api_base: https://x.services.ai.azure.com/
      api_key: ""
      api_version: "2024-10-21"
  - model_name: Mistral-7b
    litellm_params:
      model: openai/mistralai/Mistral-7B-Instruct-v0.3
      api_key: ""
      api_base: https://vllm.srvitkcaiaavllm01.itkdev.dk/v1
    guardrails:
      - message_trimming

guardrails:
  - guardrail_name: "message_trimming"
    litellm_params:
      guardrail: message_overflow.MessageTrimmingGuardrail
      mode: "pre_call"
      default_on: true
    default_config:
      trim_ratio: 0.75
      max_output_tokens: 2000
      safety_buffer: 500
      debug: true