version: '3'

# https://taskfile.dev/usage/#env-files
dotenv: [ '.env.local', '.env' ]

vars:
  # https://taskfile.dev/reference/templating/
  BASE_URL: '{{.TASK_BASE_URL | default .COMPOSE_SERVER_DOMAIN | default .COMPOSE_DOMAIN }}'
  DOCKER_COMPOSE: '{{ .TASK_DOCKER_COMPOSE | default "itkdev-docker-compose" }}'
  OPEN_WEBUI_REPO: 'https://github.com/itk-dev/open-webui.git'
  OPEN_WEBUI_VERSION: 'v0.6.26'
  TARGET_DIR: 'open-webui'
  PATCHES:
    - name: 'Adding support for redis session storeage'
      url: 'https://patch-diff.githubusercontent.com/raw/open-webui/open-webui/pull/17223.diff'

tasks:
  default:
    desc: 'List all tasks'
    cmds:
      - task --list-all
    silent: true

  compose:
    desc: "Run `docker compose` command. Example: task compose -- up --detach"
    cmds:
      - '{{ .DOCKER_COMPOSE }} {{ .CLI_ARGS }}'

  sync:tags:
    desc: "Sync tags from upstream repos"
    dir: "{{ .TARGET_DIR }}"
    cmds:
      - git remote add upstream https://github.com/open-webui/open-webui
      - git fetch --tags upstream
      - git push --tags
      - git remote rm upstream

  clone:
    desc: "Clone open-webui core"
    cmds:
      - git clone {{ .OPEN_WEBUI_REPO }}
      - git checkout {{ .OPEN_WEBUI_VERSION }}
    silent: true

  patch:
    desc: "Patch open-webui with custom patches"
    dir: "{{ .TARGET_DIR }}"
    cmds:
      - for: { var: PATCHES }
        cmd: curl -sSL {{ .ITEM.url }} | patch -p1 --no-backup-if-mismatch
    silent: true

  clean-up:
    desc: ""
    dir: "{{ .TARGET_DIR }}"
    cmds:
      - git reset --hard
      - git checkout .
      - git checkout {{ .OPEN_WEBUI_VERSION }}

  install:
    desc: "Install new web-ui"
    cmds:
      - task copy:config
      - task compose -- pull
      - task container:build
      - task compose -- up --detach --force-recreate
      - task frontend:build
    silent: true

  copy:config:
    desc: "Copy config file from example, if it does not exist"
    cmds:
      - if ! [ -f litellm_config.yaml ]; then cp litellm_config.example.yaml litellm_config.yaml; fi
      - if ! [ -f .env ]; then cp .env.default .env; fi

  container:build:
    desc: "Build container with newest requirements"
    cmds:
      - task compose -- build
    silent: true

  frontend:build:
    desc: "Build frontend"
    cmds:
      - task compose -- run --rm -it node npm ci --force
      - task compose -- run --rm -it node npm run build
    silent: true

  frontend:dev:build:
    desc: "Build frontend"
    cmds:
      - task compose -- run --rm -it -e ENV=dev node npm ci --force
      - task compose -- run --rm -it -e ENV=dev node npm run build
    silent: true

  open:
    desc: Open-webui in the browser
    cmds:
      - open http://{{ .BASE_URL }}

  prod:build:image:
    desc: Build docker image and push to docker hub
    vars:
      TAG: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}beta{{end}}'
    cmds:
      - COMPOSE_BAKE=true docker compose --file docker-compose.yml build --no-cache --pull openwebui
      - docker tag openwebui-openwebui itkdev/openwebui:{{.TAG}}
      - docker tag openwebui-openwebui itkdev/openwebui:latest
      - docker push itkdev/openwebui:{{.TAG}}
      - docker push itkdev/openwebui:latest
